isomorphic-git/isomorphic-git

package.json
=> chore(package): update rollup to version 0.51.6

karma.conf.ci.js, karma.conf.local.js, package-lock.json, package.json
as happens when others open up a PR.
=> Don't fail tests just because SauceLabs environment vars missing

src/models/GitConfig.js
=> Commit the fix for #83 as a feature branch

__tests__/test-clone.js, karma.conf.js, package-lock.json, package.json
The first of many such fantastic tests, hopefully.
=> Add a simple clone test using karma-git-http-server-middlware

__tests__/test-commit.js, src/commands/commit.js, src/models/GitConfig.js
=> fix: Throw meaningful error message from "commit" if author is missing (fixes #107)

package.json
in order to work with stackblitz/turbo-resolver
=> fix(pkg): Make the optionalDependencies be devDependencies

src/commands/log.js, src/models/GitCommit.js
The first (and hopefully last) tweak needed to address #146
=> fix: Remove instances of the Spread Properties operator

package.json
Based on the reviewed module graph, it appears that there are no side effects created against each other. (For more information on what I mean here: https://stackoverflow.com/a/49203452/1624684). 
This change will enable webpack4 to perform even deeper treeshaking and dead code elimination out of the box. (Without any breaking change).
=> chore(pkg): Add sideEffects: false flag

README.md
Closes #194.
Happy to change the placement/wording 😄
=> chore: adding link to getting started guide in readme. 

__tests__/test-basic-test.js, __tests__/test-commit.js, src/commands/commit.js, src/models/GitCommit.js
=> fix: Use local timezone by default (fixes #221)

__tests__/test-clone.js, src/commands/clone.js, src/index.d.ts
To add an argument to an existing command:
=> feat: Added new 'noCheckout' argument to clone

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, __tests__/__snapshots__/test-listFiles.js.snap, __tests__/test-listFiles.js, src/commands/listFiles.js, src/commands/pull.js, src/index.d.ts
This is a follow up on the idea I had [here](https://github.com/isomorphic-git/isomorphic-git/issues/206#issuecomment-390330460)
=> feat: Add 'ref' parameter to listFiles

src/commands/fetch.js
=> fix: Don't create empty pack/pack-.pack files

src/models/GitIndex.js
=> fix: Supply a default mode for files when adding them to the index

__tests__/__snapshots__/test-fetch.js.snap, src/managers/GitRefManager.js
Oh wow! Thanks for opening a pull request! :grin: :tada:
You are very welcome here and any contribution is appreciated. :+1:
Choose one of the checklists if it applies to you and delete the rest.
=> fixed : typo in GitRefManager

.github/PULL_REQUEST_TEMPLATE.md
People seem to be leaving this in often, I see it other projects, too. I have emojified the emoticons as they would no longer render (comments are hidden in preview) so this is for the contributor to enjoy in their full visual glory even in edit more.
=> Update PR template to remove instructions

src/managers/GitObjectManager.js, src/models/GitPackIndex.js
fixes issue https://github.com/isomorphic-git/isomorphic-git/issues/291
this PR is only draft version
=> replace array with object for performance increasing 

__tests__/test-GitPackIndex.js, src/managers/GitObjectManager.js, src/models/FileSystem.js, src/models/GitPackIndex.js
fixes https://github.com/isomorphic-git/isomorphic-git/issues/297
=> packed file await fixes

.travis.yml
skipping over 10.4.0 because of this regression https://github.com/isomorphic-git/isomorphic-git/pull/267
=> Let's see if node 10.5.0 works

package-lock.json, package.json, src/models/GitPackIndex.js, src/utils/StreamReader.js, src/utils/git-list-pack.js
Replaced git-list-pack with my own code using pako to find the object offsets in the packfile.
=> perf: speed up packfile parser and reduce bundle size

README.md
=> Update info on cors-buster based on the blog post

src/index.d.ts
=> fix: Add TypeScript information for TagDescription

.travis.yml, src/commands/getRemoteInfo.js
=> fix: add 'noGitSuffix' parameter to getRemoteInfo

.extra/git index.grammar, src/models/GitIndex.js
=> fix: fixes a bug parsing the git index when ctime is blank

README.md, __tests__/__fixtures__/test-fetch-cors.git/config, __tests__/__fixtures__/test-issue-84.git/config, __tests__/test-clone.js, package-scripts.js, src/commands/clone.js, src/commands/fetch.js, src/commands/getRemoteInfo.js, src/commands/merge.js, src/commands/pull.js, src/commands/push.js, src/index.d.ts, src/managers/GitRemoteHTTP.js
=>  feat: support 'http.corsProxy' config option

src/commands/add.js, src/commands/checkout.js, src/commands/commit.js, src/commands/status.js, src/models/FileSystem.js, src/models/GitWalkerFs.js, src/utils/normalizeMode.js, src/utils/normalizeStats.js
=> fix: handle symlinks correctly

CONTRIBUTING.md, README.md, __tests__/__snapshots__/test-exports.js.snap, __tests__/test-GitPackIndex.js, __tests__/test-writeObject.js, src/commands/writeObject.js, src/index.d.ts, src/index.js, src/managers/GitObjectManager.js, src/models/GitAnnotatedTag.js, src/models/GitObject.js, src/models/GitPackIndex.js, src/models/GitWalkerFs.js
=> feat: add 'writeObject' command

src/managers/GitObjectManager.js, src/models/GitPackIndex.js, src/utils/git-list-pack.js
=> fix: handle corrupt packfiles more gracefully

rollup.config.js, src/commands/fetch.js, src/commands/push.js, src/utils/filterCapabilities.js
=> fix: pushing to AWS CodeCommit compatibility

src/commands/push.js, src/managers/GitRefManager.js, src/models/GitIndex.js, src/models/GitPackIndex.js, src/storage/writeObjectLoose.js
=> fix: bug in packfile caching code (resolves #439)

azure-pipelines.yml, src/commands/listObjects.js, src/models/GitTree.js
=> [WIP] don't crash when pushing commits referencing submodules

__tests__/__snapshots__/test-exports.js.snap, azure-pipelines.yml
=> ci: fix Azure test reporting

.github/PULL_REQUEST_TEMPLATE.md, __tests__/__helpers__/karma-pr-comment-reporter.js, __tests__/test-push.js, azure-pipelines.yml
=> chore: Update PR template with squash merge instructions

src/managers/GitRemoteHTTP.js
=> fix: Fixes cloning from Gogs by not sending a custom User-Agent (fix #555)

azure-pipelines.yml
https://developercommunity.visualstudio.com/content/problem/350007/build-from-github-pr-fork-error-tf400813-the-user-1.html
=> don't run PublishBuildArtifact or PublishCodeCoverageResults for PRs

.babelrc, package-lock.json, package.json, src/models/GitConfig.js
For some reason, Object spread properties are still causing trouble, particularly with https://bundlephobia.com/.  Therefore, I'm changing the one object spread property to an Object.assign.
=> fix: remove stray {...object}

package-lock.json, package.json, src/managers/GitRemoteHTTP.js
fix #555 (hopefully for real this time)
=> fix: better browser vs node detection

README.md, package-lock.json, package.json, src/managers/GitRemoteHTTP.js
=> Third time

src/utils/log.js
=> fix: reference to window.localStorage broke WebWorker

webpack.config.js
=> fix: set UMD build to target 'webworker'

package-lock.json, package.json, src/models/GitPackIndex.js, src/models/GitSideBand.js, src/wire/writeReceivePackRequest.js, src/wire/writeRefsAdResponse.js, src/wire/writeUploadPackRequest.js
fixes #601
This _shouldn't_ adversely affect anything. We'll find out.
=> fix: depend on 'readable-stream'

src/commands/clone.js
=> fix: pass core to fetch function

__tests__/test-checkout.js, src/commands/checkout.js
=> fix: write executable file so it honors the system umask

src/commands/fetch.js
=> fix: consolidate ref filter in fetchPackfile

src/index.d.ts
fixes #681
For example:
```
$ tsc -p .
node_modules/isomorphic-git/src/index.d.ts:188:9 - error TS7051: Parameter has a name but no type. Did you mean 'arg0: string'?
188   get: (string) => GitPluginCore;
~~~~~~
node_modules/isomorphic-git/src/index.d.ts:189:12 - error TS7051: Parameter has a name but no type. Did you mean 'arg0: string'?
189   create: (string) => GitPluginCore;
~~~~~~
Found 2 errors.
```
=> fix: eliminate TS7051 errors generated by typescript compiler

package.json, src/managers/GitRemoteHTTP.js, src/utils/http-browser.js, src/utils/http.js, webpack.config.js
I WANT TO SEE THAT 18% DROP 👀 
Edit: well, 15.7% drop. Whatever it is
=> fix: simplify Webpack config so bundlephobia excludes readable-stream

package-lock.json, package-scripts.js, package.json, rollup.config.js
=> Vanity bundlephobia2

src/commands/fetch.js, src/storage/hasObject.js, src/storage/hasObjectLoose.js, src/storage/hasObjectPacked.js, src/utils/emptyPackfile.js
=> fix: more efficient fetch after clone

azure-pipelines.yml, src/commands/checkout.js, src/managers/GitRefManager.js
try this thing https://medium.com/microsoft-1es/reducing-vs-code-ci-build-times-e0c5872bfdde
=> chore: cache node_modules folder in CI

src/commands/checkout.js
As kindly pointed out by @nelsonni here https://github.com/isomorphic-git/isomorphic-git/commit/667ae6c6758a3f385a5734f1fa4c9a64cb9a14bf#r33219402
=> fix: remove stray console.log in "checkout" command

src/managers/GitRemoteHTTP.js, src/utils/calculateBasicAuthUsernamePasswordPair.js
=> fix: don't throw for URLs with an embedded username but no password

__tests__/__helpers__/generate-docs.js
=> fix: escape pipes

package-lock.json, package.json
Vulnerable versions: < 3.5.0
Patched version: 3.5.0
A vulnerability was found in diff before v3.5.0, the affected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS) attacks.
=> address vulnerability in "diff" dependency (via "diff-lines")

src/utils/AsyncIterator.js
=> fix: improve AsyncIterator feature detection

src/commands/merge.js, src/commands/pull.js, src/index.d.ts
=> fix(pull): Added 'author', 'committer', 'signingKey' parameters

__tests__/test-GitError.js, __tests__/test-GitIndex.js, __tests__/test-GitObjectManager.js, __tests__/test-GitPackIndex.js, __tests__/test-GitRefManager.js, __tests__/test-addRemote.js, __tests__/test-branch.js, __tests__/test-checkout.js, __tests__/test-deleteBranch.js, __tests__/test-deleteRemote.js, __tests__/test-deleteTag.js, __tests__/test-exports.js, __tests__/test-fetch.js, __tests__/test-flatFileListToDirectoryStructure.js, __tests__/test-getRemoteInfo.js, __tests__/test-listBranches.js, __tests__/test-listCommitsAndTags.js, __tests__/test-listFiles.js, __tests__/test-listObjects.js, __tests__/test-listTags.js, __tests__/test-log.js, __tests__/test-push.js, __tests__/test-readObject.js, __tests__/test-remove.js, __tests__/test-resetIndex.js, __tests__/test-resolveRef.js, __tests__/test-writeRef.js
VS Code highlights my test files in red after I open them. I keep thinking there's a problem with my test but it's just TS yelling about `.snap` files.
=> chore(tests): tsignore snapshot imports

__tests__/test-commit.js, __tests__/test-merge.js, src/commands/commit.js, src/commands/merge.js, src/index.d.ts
=> feat: Added 'dryRun' to commit and 'noUpdateBranch' to merge

src/commands/isDescendent.js, src/commands/listCommitsAndTags.js
=> fix(merge): fix 'Failed to read git object' errors caused by shallow commits

src/commands/isDescendent.js
=> fix: remove stray console.logs

README.md
> if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
It's just a small typo on the readme, adding me into contributors is not really necessary. ;)
=> Update the issue link of CORS support for Gitlab

src/models/GitWalkerRepo.js
without changing any existing behaviors AFAICT.
=> perf(walker): speeds up walking git repos

src/models/GitConfig.js
=> fix: config section and variable names are allowed to have - not _

__tests__/__helpers__/FixtureFS/makeBrowserFS.js, __tests__/__helpers__/fix-version-number.js, __tests__/__helpers__/jasmine-snapshots.js, __tests__/env.d.ts, __tests__/index.webpack.js, __tests__/test-branch.js, __tests__/test-cores.js, __tests__/test-deleteBranch.js, __tests__/test-deleteRemote.js, __tests__/test-deleteTag.js, package-lock.json, package.json, src/index.d.ts
Goal: fewer red squiggles in VS Code.
=> chore: improve internal typings

README.md
Stoplight Studio uses isomorphic-git 🎉
=> chore: add Stoplight Studio to list of apps

src/commands/statusMatrix.js, src/index.d.ts
=> feat(statusMatrix): Added 'noSubmodules' param

__tests__/test-push.js, src/commands/push.js, src/index.d.ts
=> feat(push): Added 'delete' param

__tests__/test-push.js, src/commands/push.js
=> fix(push): update local copy of remote refs

src/models/GitPackIndex.js
The time to run `indexPack` on a 16 MB packfile with ~9000 objects went from ~39 seconds to ~8 seconds. `marky`'s Node implementation was O(1) but in the browser it was O(N) due to the use of `getEntriesByName()` and my reusing `name` in a loop.
I love Chrome's profiler.
=> perf(fetch, clone, indexPack): remove profiling code that had a linear overhead

src/commands/push.js, src/errors/AlreadyExistsError.js, src/errors/AmbiguousError.js, src/errors/ObjectTypeError.js, src/errors/PushRejectedError.js, src/errors/RemoteCapabilityError.js
Tighten up some of the types and enums.
=> fix: tweak error types

.gitignore, __tests__/__helpers__/generate-docs.js, azure-pipelines.yml, docs/alphabetic.md, docs/guide-webworker.md, docs/http.md, package-scripts.js, website/i18n/en.json, website/sidebars.json
fixes a couple bugs in the docs website
=> chore: fix the docs website

README.md
Some lines had them, some didn't, now none do because there was more of the ones that didn't and this is a democracy.
=> Harmonize the semicolons in code examples

website/blog/2020-02-25-version-1-0-0.md
=> Fix text for OpenDevise link in acknowlegements section

__tests__/test-statusMatrix.js, src/api/statusMatrix.js
=> fix: pass wrapped fs to GitIgnoreManager.isIgnored (#1076)

__tests__/test-readObject.js, src/api/readObject.js
fixes #1080
It's technically a breaking change... but it's one I talk about _several_ times in the docs and release notes, and the fact that I forgot to make it... well... gosh I hope this doesn't screw anybody up 🤞.
=> fix(readObject): should return TreeObject not { entries: TreeObject }

src/api/indexPack.js, src/commands/indexPack.js, website/versioned_docs/version-1.x/indexPack.md
=> feat(indexPack): return the oids contained in packfile

README.md
=> broken link to cors-proxy on npm

__tests__/test-findMergeBase.js, package.json, src/commands/findMergeBase.js, src/commands/push.js
This is a proposition to fix #1131
=> perf(push, findMergeBase): improve find merge base speed

cli.js, src/commands/listCommitsAndTags.js, src/commands/listObjects.js, src/commands/push.js, src/managers/GitRefManager.js
This is a very naïve proposition to fix #1134. It works on the two projects we tried it on but it's just a conversation starter on how to fix this.
=> perf(push): send thin packs when possible

website/siteConfig.js, website/static/js/announcement.js
All technology is political; if you have a platform use it. 
I'm in no way being original here... frankly I'm ashamed it took me so long.
I would like to thank ExpressJS and MobX for inspiration:
=> #BlackLivesMatter

.all-contributorsrc, README.md, src/commands/pull.js
This fixs https://github.com/isomorphic-git/isomorphic-git/issues/1124
=> fix: Cannot read property 'index' of undefined when "Pull"

src/commands/listObjects.js
=> fix(push): fix regression introduced in v1.4.4, pushing repos with submodules broke

__tests__/test-getRemoteInfo.js, __tests__/test-getRemoteInfo2.js, __tests__/test-push.js, src/api/getRemoteInfo.js, src/api/getRemoteInfo2.js
=> fix(getRemoteInfo, getRemoteInfo2): throw UnknownTransportError for SSH urls

.github/PULL_REQUEST_TEMPLATE.md
=> docs(pr-template): fixed location of `__tests__/test-exports.js`

src/api/packObjects.js, src/commands/fetch.js, src/commands/packObjects.js, src/commands/push.js, src/managers/GitRemoteHTTP.js
Should fix #1231
I actually haven't been able to reproduce it yet 😬 but I _think_ based on the stack traces I've seen at Stoplight that this will fix it.
=> fix(push): "Cannot read property 'packfiles' of undefined" error

website/i18n/en.json, website/static/js/try-it-out-giturl.js
=> fix(website): try it out

src/utils/mergeTree.js
potential fix for https://github.com/stoplightio/platform-internal/issues/5366
=> fix(merge): Cannot set property 'oid' of undefined

.all-contributorsrc, README.md, package-lock.json, package.json
I also had to bump the all-contributors-cli package since apparently I used a more recent version last time I ran it and the devDep was for an older version that has the redundant alt tags.
=> docs: add @Ry0taK as a contributor

.gitignore, README.md, __tests__/test-exports.js, docs/alphabetic.md, src/api/isIgnored.js, src/index.js, website/sidebars.json, website/versioned_docs/version-1.x/alphabetic.md, website/versioned_docs/version-1.x/isIgnored.md, website/versioned_sidebars/version-1.x-sidebars.json
=> feat: Added 'isIgnored' command

docs/onAuth.md
docs update. I spent a half hour trying to figure out why my code wasn't working lol. Shouldn't have trusted my docs :facepalm:
=> chore: update onAuth docs

src/wire/parseRefsAdResponse.js
Stoplight customer reported the following error in Studio Desktop:
I was unable to reproduce but close analysis of the code leads me to believe this is the only possible explanation 🤷🏻 .
=> fix: handle protocol version 2 edge case

__tests__/test-GitConfig.js, src/models/GitConfig.js
=> fix: update the config parser to handle dots in key name

__tests__/test-checkout.js, src/api/checkout.js, src/commands/checkout.js, website/versioned_docs/version-1.x/checkout.md
=> feat: add `noTrack` option to checkout

package-lock.json, package.json
=> chore(deps): bump simple-get from 3.0.3 to 4.0.0

src/api/checkout.js
- fix type
- fix default value
- fix description
=> fix documentation for track option on checkout command

README.md, package.json
=> fix Android image in README

docs/faq.md
I'm adding documentation so that users understand how to use isomorphic-git with an HTTP proxy.
=> document how to get isomorphic-git to use the HTTP proxy

website/pages/en/index.js
- [ x ] squash merge the PR with commit message "fix: [Description of fix]"
Go from
to
=> fix: update android logo

src/commands/checkout.js
=> chore: fix typo in checkout.js

__tests__/test-add.js, src/api/add.js, src/errors/MultipleGitError.js, src/managers/GitIndexManager.js, website/versioned_docs/version-1.x/add.md
This PR requires https://github.com/isomorphic-git/isomorphic-git/pull/1507
=> feat: add supports array of files

__tests__/__helpers__/generate-docs.cjs
This PR fixes an intermittent problem running `npm test`. The `build.docs` step fails intermittently when the temporary directory returned by `os.tmpdir()` includes a directory that starts with an underscore. For example, on MacOS I see:
```
$ node
> os.tmpdir()
'/var/folders/_g/4819ldps2g51js0fsbnv5b_40000gn/T'
^ 
```
Before:
After:
=> fix: build.docs should not fail when the temporary directory starts with _

src/api/add.js
restore fix that was reverted by e2defd26313789141d7bbd9d0ab143005f79ab38
=> restore fix for #1381

__tests__/test-walk.js, src/commands/TREE.js
=> fix(TREE): add default value to sole argument of TREE function

CONTRIBUTING.md
=> add another resource to Contributing file

CONTRIBUTING.md
=> add another github blog article

karma.conf.cjs
=> (chore) fix remote browser timeout in karma file

docs/authentication.md
I removed all the header stuff (since it's not in the `push` function anymore) and added notes on adding it to the URL or using `onAuth`
Related: #1722
=> This addresses changes to auth API #1722

README.md
=> add Project status to readme

LICENSE.md
=> fix: force CI/CD to Release new version

.all-contributorsrc, src/http/node/index.js, src/wire/parseUploadPackResponse.js
=> fix: Handle promise resolution/rejection

src/utils/deflate.js
Otherwise resources are left dangling
=> The test stream needs to be closed

__tests__/test-hosting-providers.js
As discussed in https://github.com/isomorphic-git/isomorphic-git/issues/1876#issuecomment-1999378066 we'll disable the test to unblock PRs.
=> test: Disable failing test

.gitattributes, package-lock.json, package.json, src/utils/StreamReader.js
This fixes main issue with #1855
=> fix: Missing Buffer Error

__tests__/test-hosting-providers.js
=> chore: disable gitlab tests

.all-contributorsrc, README.md, website/versioned_docs/version-1.x/onAuth.md
=> fix: update Github App auth details in `onAuth` docs

.github/PULL_REQUEST_TEMPLATE.md
The squash happen when you merge the PR
=> Remove Squash from PR GH template

__tests__/test-push.js, src/api/push.js, src/commands/push.js
fixes #1900
I added comments below on my changes. You feedback is welcome!
=> fix: push tag: do not update remote ref

docs/guide-quickstart.md
=> docs: Update guide-quickstart.md

azure-pipelines.yml
=> chore: increase timeout

website/versioned_docs/version-1.x/guide-quickstart.md
=> chore: Update guide-quickstart.md

src/api/updateIndex.js, src/commands/walk.js, src/managers/GitIndexManager.js, src/models/GitWalkerFs.js
General performance improvements that originally came from this [PR](https://github.com/isomorphic-git/isomorphic-git/pull/2023)
=> perf: general performance improvements

azure-pipelines.yml
=> chore: update Azure VM

karma.conf.cjs
=> chore: update Android testing target on BrowserStack

package-lock.json, package.json
Update sha.js dependency, to fix security issue in direct dependencies.
Closes: #2178
=> fix: update sha.js
