src/index.d.ts
There were three types of problems:
`TS1040: 'async' modifier cannot be used in an ambient context`
This means the modifier `async` was included in the types incorrectly. If this was an interface and not a type declaration, you'd leave it up to the implementer to either use an `async` function or one that returns a `Promise` directly. In the same way, as long as the function returns a `Promise`, it's `await`able and it does not matter what the actual implementation is from the point of view of the type declaration.
`TS6137: Cannot import type declaration files. Consider importing 'events' instead of '@types/events'.`
This is a simple problem, we import `events` as we would, the fact that we import it only for types does not matter. TypeScript understands that.
`TS1254: A 'const' …
=> Fix TypeScript 2.7.2 reported errors in the type declarations

LICENSE.md, README.md, package.json
The consensus seems to be that using the standard MIT License will be more friendly to users and businesses than the Unlicense. I'm pretty sure that I, being the author, can relicense it this way. In jurisdictions where the public domain dedication was never valid, I still have the copyright. And in jurisdictions where the code became part of the public domain, I am free to include the text in my own work.
=> fix: Switch from The Unlicense to The MIT License

__tests__/test-findRoot.js, package-lock.json, package.json
* use fork of jest-fixtures that doesn't have "/tmp" hard-coded
* remove test that fails when the user's home directory contains a .git folder
=> Makes sure tests work on Windows

README.md
Since I've already gotten 2 PRs dealing with badges, and the current layout is asking for git merge conflicts, this PR separates them onto their own lines. And organizes them some.
=> Organize badges

.travis.yml, __tests__/test-GitRefSpecSet.js, __tests__/test-fetch.js, package-scripts.js, src/commands/fetch.js, src/managers/GitRefManager.js
This is a (surprisingly complicated) set of changes so that when you do `isogit clone --singleBranch` you end up with the same entries in `remotes/origin` as you do when you run `git clone --single-branch`. 
- It doesn't update the references until _after_ the packfile is downloaded. Before, it erroneously reported having all the refs!
- It now saves the remote `HEAD` to `remotes/origin/HEAD` if you clone the default branch, even though that's not in the git config refspec (🤷‍♂️ ).
- If you clone with `singleBranch: true` it only saves the refs (and symrefs) for the branch you download.
**This should fix some of the spurious errors with `clone` and `checkout` we have been seeing!**
=> fix: only update remote refs that we actually have downloaded

__tests__/test-GitPackIndex.js, src/models/FileSystem.js, src/models/GitPackIndex.js
the branch name is a misnomer. True lazy parsing would only access the file on readObject and only parse the relevant entries in the idx file. This is just me speeding up the existing eager idx parser.
=> perf: do less parsing of idx files to save time

src/commands/status.js, src/models/GitIndex.js, src/utils/compareStats.js, src/utils/normalizeStats.js
I think to see real perf improvements though, I need to support calling `git.status` on whole directories at a time (because status requires walking the HEAD commit, and it's better to walk just once).
=> fix: cache stat values after calling git.status

package-lock.json, package.json
I noticed as I was updating my [tutorial](https://runkit.com/wmhilton/5a89cd94303ded001277664c) that the ‘isomorphic-git’ package is out of date on runkit. Runkit is stuck at version v0.12.3.
I contacted Runkit and was told:
>  Unfortunately, we've temporarily disabled natively-compiled packages to prevent abuse and attacks on our infrastructure. We're eagerly looking forward to re-enabling this and re-processing native-code packages, but unfortunately do not have a timeline just yet.
Obviously, isomorphic-git is pure JavaScript. Jest has some native modules (for real, it's sad) however v0.12.3 uses Jest as well so that's probably not it. Two packages were added in the v0.13.0 release:
- git-clean-ref
- opencollective
OpenCollective *does* have a postinstall script that prints a message. …
=> see if removing opencollective postinstall script fixes runkit

src/commands/merge.js, src/index.d.ts
The documentation erroneously said the 'ours' parameter was optional. Now it actually is.
=> fix: Make the 'ours' parameter of merge optional

src/index.d.ts
It's not just a nuisance, since TypeScript complains when 'filepath' is not given, but you have to omit it in order to be able to get readObject to return commit objects.
=> Mark readObject's arguments 'format', 'filepath' and 'encoding' as optional because they are.

src/commands/getRemoteInfo.js, src/index.d.ts
Needed for debugging #310. Turns out the list of supported capabilities a server returns (and the list of refs potentially) depends on whether you express interest in pushing or pulling.
=> feat: Added 'forPush' parameter to getRemoteInfo command

__tests__/test-push.js, src/commands/push.js, src/index.d.ts, src/managers/GitRefManager.js
Fixes #348
Just a quick & dirty patch to make this work:
```js
git.push({ ...pushDetails, ref: 'feature-branch:refs/heads/master' }))
```
=> feat: Push a local branch/tag to a differently named branch/tag on the remote

src/commands/resetIndex.js
=> fix: add 'fs' plugin compatibility to "resetIndex" command

src/commands/walkBeta1.js, src/index.d.ts
That was about as hard as I expected. ☹️ Not sure if they're 100% correct.
This part is easy:
```ts
export interface Walker {}
export function WORKDIR(args: {
fs: any;
dir: string;
gitdir: string;
}): Walker;
export function TREE(args: {
fs: any;
gitdir: string;
ref: string;
}): Walker;
export function STAGE(args: {
fs: any;
gitdir: string;
}): Walker;
```
> Note: in the future, the 'fs' argument may be optional now that we have the plugin system.
This next part is awkward because almost all the props are marked optional. Maybe in `walkBeta2` I'll have the `.populate` methods return a new object instead of modifying the current one? Then we can provide stronger assertions by making the return type equal to the current type + some new properties. (Something like `populateHash: () => this & …
=> add TypeScript definitions for walkBeta1

src/commands/fetch.js, src/commands/push.js, src/index.d.ts
=> feat: include HTTP headers in the results for fetch and push

README.md, src/models/GitObject.js, src/wire/parseRefsAdResponse.js, src/wire/writeReceivePackRequest.js, src/wire/writeRefsAdResponse.js
The following error on bundlephobia:
```
main.bundle.js from Terser
Octal escape sequences are not allowed in template strings
[main.bundle.js:19699,22]
```
Since terser is the new uglify-es and Webpack is slated to start using it (or already is, I'm not sure) we can't have terser throwing parsing errors. As it turns out
```js
`${type} ${object.byteLength.toString()}\0`
```
isn't actually valid JavaScript. Because `\0` is technically an octal escape sequence, and those are forbidden in strict mode (and all ES6 modules are run in strict mode) and in template strings. So... who knows why this hasn't been a problem until now. I guess all the JavaScript parsers have been forgiving. Or maybe `\0` technically _isn't_ an octal escape sequence and deserves some special treatment that `terser` …
=> fix: Octal escape sequences are not allowed in template strings

src/commands/checkout.js, src/commands/clone.js, src/commands/fetch.js, src/commands/indexPack.js, src/index.d.ts, src/models/GitPackIndex.js
fixes #596
This PR adds more events and adds a 'phase' to the events. So you can drive pretty progress bars like this:
=> fix: add 'phase' to progress events

__tests__/test-init.js, src/commands/init.js, src/index.d.ts
=> feat: Added 'bare' parameter to init command

src/commands/fetch.js
=> fix: avoid unnecessary match if emitter is not defined

src/commands/fetch.js, src/wire/parseUploadPackResponse.js
fixes #624 Issue was through2 stopped reading from packetlines after the highWaterLimit (~16kb)
=> fix: fixed crash when shallow cloning certain repositories

src/commands/currentBranch.js
only execute a single regular expression to clean the refname
=> fix: optimize abbreviate in 'currentBranch'

src/commands/annotatedTag.js, src/commands/clone.js, src/commands/commit.js, src/commands/fetch.js, src/commands/getRemoteInfo.js, src/index.d.ts, src/utils/normalizeAuthorObject.js
=> fix: add 'headers' param to clone, fetch, and getRemoteInfo

src/utils/normalizeStats.js
(useful for simplifying `lightning-fs`)
=> fix: use 'mtimeMs' if available instead of 'mtime.valueOf'

src/index.d.ts
It looks like there were two interfaces defined by mistake with the same name `RemoteDescription`, and that name is used in return type for `listBranches()` and `getRemoteInfo()` functions. According to the code, only one of the `RemoteDescription` types is correct for `listBranches()` function. 
I renamed the one that `listBranches()` returns to `RemoteDefinition` (as a set of url and name defines the remote, but does not describe it in detail), and left `RemoteDescription` type as a return for `getRemoteInfo()`.
Looks like it was a simple mixup.
=> fix: listRemotes function return type was incorrect.

__tests__/test-walkBeta1.js, src/utils/log.js
=> fix: don't error if process.env is undefined

src/index.d.ts
https://isomorphic-git.org/docs/en/addRemote
`force` is an option in the docs but not in the typings.
=> fix: add force to addRemote typings

__tests__/__helpers__/FixtureFS/makeLightningFS.js, karma.conf.js, src/index.d.ts, src/models/FileSystem.js, src/utils/plugins.js
This adds slight (probably not measurable) perf improvement but more importantly, simplifies creating a wrapped `fs` plugin that (say) emits events to emulate a file watcher. 👀
=> feat: prefer fs.promises over wrapping fs with pify

src/utils/http-browser.js
The browser HTTP plugin is returning [`Headers`](https://developer.mozilla.org/en-US/docs/Web/API/Headers) not [`headers`](https://nodejs.org/api/http.html#http_message_headers) like the node plugin. I discovered this because `Headers` objects are not clonable and thus the result of `push` and `fetch` can't be returned via `postMessage` without an error. Which is bad.
=> fix: the `headers` returned by the HTTP plugin should be JSON

__tests__/__helpers__/generate-docs.js
update to `generate-docs.js`
This is so when people click the "Edit" button on the docs page,
they won't be taken to the raw Markdown. Since the Markdown is generated _from_ the JSDoc, it makes more sense for them to be taken to the actual JS file.
=> chore: rewrite "Edit" button link in docs

__tests__/test-status.js, __tests__/test-statusMatrix.js, src/commands/status.js, src/models/GitWalkerRepo.js, src/storage/readObject.js, src/utils/resolveTree.js
=> fix: support 'status' and 'statusMatrix' on empty branches

src/index.d.ts
=> fix: strengthen typings for git.log

src/models/FileSystem.js, src/utils/plugins.js
fixes #771
```js
> node
> require('.').plugins.set('fs', require('fs'))
undefined
> (node:8427) ExperimentalWarning: The fs.promises API is experimental
(To exit, press ^C again or type .exit)
>
```
```js
> node
> require('.').plugins.set('fs', require('fs'))
undefined
>
(To exit, press ^C again or type .exit)
>
```
---
This exploits the fact that there is a subtle difference between how `fs.promises` is exposed in v10 (which prints a warning) and v12 (which does not)
v10
```js
> Object.getOwnPropertyDescriptor(fs, 'promises')
{ get: [Function: get],
set: undefined,
enumerable: false,
configurable: true }
```
v12
```js
> Object.getOwnPropertyDescriptor(fs, 'promises')
{
get: [Function: get],
set: undefined,
enumerable: true,
configurable: true
}
```
LightningFS
```js
> …
```
=> fix: remove 'ExperimentalWarning: The fs.promises API is experimental'

__tests__/test-merge.js, src/commands/merge.js, src/index.d.ts, src/models/FileSystem.js, src/utils/plugins.js
=> feat: Added 'dryRun' parameter to merge command

__tests__/__helpers__/FixtureFS/makeBrowserFS.js, __tests__/__helpers__/FixtureFS/makeLightningFS.js, __tests__/__helpers__/FixtureFS/makeNodeFixture.js, __tests__/test-add.js, __tests__/test-unicode-paths.js, azure-pipelines.yml, karma.conf.js, src/managers/GitIndexManager.js, src/models/FileSystem.js, src/utils/DeepMap.js
This speeds up running `statusMatrix` on large repos like https://github.com/ianstormtaylor/slate from ~80 seconds to ~1 second. (These times measured on a proprietary Electron app. How big the perf hit is depends highly on the latency of the filesystem... on Electron the latency is very bad because it is proxied to the worker over IPC.)
It does caching based on the compound key `[fs, filepathOfIndexFile]`. It uses `lstat` to determine whether the index file has been modified. 99% of the time this should be enough! However... if you  are "resetting" a filesystem mock behind the scenes (like my BrowserFS tests were), that might not be enough. In such cases that the index file returns the same `stat` information but it actually has changed different, then your tests may too fail. (This …
=> perf: cache .git/index for better performance

__tests__/__helpers__/FixtureFS/makeNodeFixture.js, __tests__/test-utils-join.js
should fix #783
My Windows machine is borked at the moment (keeps trying to use Python 3 with gyp...) so I can't actually test whether it's working.
=> fix: tests weren't passing in Windows

src/commands/pull.js, src/index.d.ts
=> feat: Added 'corsProxy' parameter to pull command

__tests__/test-commit.js, src/commands/commit.js, src/index.d.ts
=> feat: Added 'parent' parameter to commit command

__tests__/test-commit.js, src/commands/commit.js, src/index.d.ts
=> feat: Added 'tree' parameter to commit command

__tests__/__helpers__/FixtureFS/makeBrowserFS.js, __tests__/__helpers__/FixtureFS/makeLightningFS.js, __tests__/__helpers__/FixtureFS/makeNodeFixture.js
I don't understand why `standard` caught this on Windows but not on Mac or Linux. But... I see no reason to disagree with it.
=> chore: fix linting on Windows

src/commands/fetch.js
I believe this fixes the root cause of #788.
=> fix(fetch): remove 'thin-pack' from advertised capabilities

src/models/GitWalkerFs.js
=> fix(walkBeta1): fix error if `.populateHash` is called without calling `.populateStat` first

.all-contributorsrc, README.md, __tests__/test-init.js, src/commands/init.js, src/index.d.ts
resolves #899 
running this made no changes, I got:
$ npm run add-contributor
> isomorphic-git@0.0.0-development add-contributor /Users/david/projects/isomorphic-git/isomorphic-git
> nps contributors.add
nps is executing `contributors.add` : all-contributors add
is/are invalid contribution type(s)
The script called "contributors.add" which runs "all-contributors add" failed with exit code 1 https://github.com/sezna/nps/blob/v5.9.8/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! isomorphic-git@0.0.0-development add-contributor: `nps contributors.add`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the isomorphic-git@0.0.0-development add-contributor script.
npm ERR! This is probably not a problem with npm. There is likely additional …
=> resolves #899 do not overwrite existing .git/config on init

__tests__/__helpers__/add-contributor.js, package-lock.json, package-scripts.js, package.json
Apparently `all-contributors-cli` is not interactive anymore. What a loss! Anyhow, I re-made it interactive. It's kinda hacky but it'll have to do until https://github.com/all-contributors/all-contributors-bot/issues/252 gets resolved.
Hopefully this will alleviate [the problems](https://github.com/isomorphic-git/isomorphic-git/pull/900) encountered by new contributors.
=> chore: fix 'npm run add-contributor' script

src/commands/fastCheckout.js, src/index.d.ts
Fixes a bug where the use of `fastCheckout({ fs, dir, files })` to restore files resulted in a detached HEAD state which was not intended at all.
ɪᴛ's ᴛᴇᴄʜɴɪᴄᴀʟʟʏ ᴀ ʙʀᴇᴀᴋɪɴɢ ᴄʜᴀɴɢᴇ ʙᴜᴛ ʜᴏᴘᴇғᴜʟʟʏ ɴᴏʙᴏᴅʏ ᴡɪʟʟ ɴᴏᴛɪᴄᴇ sɪɴᴄᴇ I ᴏɴʟʏ ᴘᴜʙʟɪsʜᴇᴅ ғᴀsᴛᴄʜᴇᴄᴋᴏᴜᴛ ʏᴇsᴛᴇʀᴅᴀʏ
=> fix(fastCheckout): bug in `noUpdateHead` logic and add missing TS types

__tests__/test-GitIndex.js, __tests__/test-GitPackIndex.js, __tests__/test-fastCheckout.js, src/commands/fetch.js, src/commands/indexPack.js, src/managers/GitIndexManager.js, src/models/GitIndex.js, src/models/GitPackIndex.js, src/models/GitWalkerFs.js, src/models/GitWalkerFs2.js, src/storage/hashObject.js, src/storage/readObject.js, src/storage/writeObject.js, src/utils/git-list-pack.js, src/utils/shasum.js, src/utils/toHex.js
Add progressive enhancement to use `crypto.subtle.digest` if is available instead of the pure JS implementation in `sha.js/sha1`.
I must say, I'm super pleased at how far I’ve come with `isomorphic-git`. For a loooooong time, I was picking such low-hanging fruit when it came to performance, and all the performance issues were async. The bottlenecks were file IO/IndexedDB, serial vs concurrent, concurrent but with head-of-line-blocking problems, and insufficient caching. To have reached the point where the synchronous hashing speed is the bottleneck feels AMAZING.
=> perf(shasum): use SubtleCrypto.digest if available

src/managers/GitRemoteHTTP.js
=> fix(http): if 'oauth2format' is set, silently strip credentials from URLs rather than error

src/models/GitTree.js, src/models/GitWalkerIndex2.js
=> fix(statusMatrix): fix a bug in walkBeta2 that returned doubled entries

.all-contributorsrc, README.md, __tests__/test-wire.js, src/wire/parseRefsAdResponse.js
This fixes the 3 places in parseRefsAdResponse I see where the result of split(sep) is assumed to have two elements.  I'm throwing a hopefully informative error including the actual problematical response line.
There's one test for missing `\0`, one for missing space, and one for double space.
Currently the error message doesn't display the `\0` separator visibly, is there an easy way to do this?
I'm happy to squash the tests into the code change if desirable.
fixes #911
=> resolves #911 handle unexpected response better

__tests__/test-wire.js, src/managers/GitRemoteHTTP.js, src/models/GitError.js
`E.RemoteDoesNotSupportSmartHTTP` was originally intended to be a more helpful error than `E.AssertServerResponseFail`. But it has become apparent that it is often a red herring, leading people down the rabbit hole of investigating "smart" vs "dumb" HTTP, and does their server support it, when in reality they simply entered a wrong URL and the remote is responding with an HTML page.
To make this scenario easier to recognize, now `E.RemoteDoesNotSupportSmartHTTP` will include a snippet from the HTTP response in the error message. (The complete response is available in the error `data` property.)
=> fix(fetch): handle HTML server response better

__tests__/test-writeObject.js, src/models/GitTree.js, src/utils/compareTreeEntryPath.js
It turns out the proper sort order of `config`, `config0`, and `config.txt` in a Git Tree if `config` is a directory is:
- `config.txt`
- `config`
- `config0`
because git adds a virtual trailing slash to directory names, and in ASCII ordering `.` comes before `/` comes before `0`.
=> fix: resolve "treeNotSorted: not properly sorted" git fsck error

__tests__/__fixtures__/test-fetch-cors.git/config, __tests__/test-fetch.js, src/commands/clone.js, src/commands/fetch.js, src/commands/pull.js, src/commands/push.js, src/index.d.ts, src/managers/GitRemoteManager.js, src/models/GitConfig.js, src/utils/translateSSHtoHTTP.js
=> feat(fetch, push, clone, pull): add autoTranslateSSH param

src/commands/checkout.js, src/commands/clone.js, src/index.d.ts
Maybe-fix for #942. Let me know if you are okay with this. I didn't have time to add a test case as I was editing this in the GitHub web UI. Feel free to add one or wait for me to add it, I'll try to take a look at this again.
I don't think the tests are failing because of me so I'm not looking into that closely.
=> Provide a noSubmodules switch for clone to avoid logging the no submodule support error

src/managers/GitRemoteManager.js
=> fix: include 'suggestion' in UnknownTransportError for SSH urls

src/commands/pull.js, src/index.d.ts
=> Add noSubmodules to pull as well

karma.conf.js, src/commands/pack.js, src/models/GitPackIndex.js, src/storage/readObject.js, src/storage/writeObject.js, src/utils/deflate.js, src/utils/inflate.js
A progressive enhancement to use `new DecompressionStream('deflate')` and `new CompressionStream('deflate')` if is available instead of the pure JS implementation in pako.
Chrome 80 has signaled an [intent to ship](https://groups.google.com/a/chromium.org/forum/m/#!topic/blink-dev/JmwpHPTu3XM) with them.
I have not bothered to measure if there is a performance difference. The simple fact that the compression/decompression happens in a separate thread pretty much guarantees it'll be a win for browser users.
`pako` is still needed to index packfiles, because so far only `pako`'s direct port of zlib's streaming implementation has the quirky ability to detect the end of `deflate` data in the middle of a stream.
=> perf: use native browser 'deflate' if available

__tests__/__helpers__/tweet.js
This bug has been driving me nuts.
=> fix: trim multi-line commit messages when tweeting about release

__tests__/test-checkout.js, __tests__/test-fastCheckout.js, src/commands/checkout.js
=> fix(checkout): files that don't match filepaths/pattern should be left alone

azure-pipelines.yml
```
Starting: Update website
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.163.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
(node:7302) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:7302) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:7302) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:7302) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:7302) Warning: Use Cipheriv for counter mode of …
```
=> chore(website): Error: Failed to replace env in config: ${NPM_TOKEN}

README.md
=> fix: broken README images on npm

README.md, __tests__/test-statusMatrix.js, __tests__/test-submodules.js, package-lock.json, package.json, src/commands/statusMatrix.js, src/index.d.ts, src/utils/patternRoot.js
BREAKING CHANGE: the `pattern` param added two dependencies to the project (globrex and globalyzer) for very little benefit since we haven't ended up using globbing anywhere else in the library. The same result can be achieved via the new function parameter `filter` which lets you provide the pattern-matching logic yourself.
=> chore: replace statusMatrix's `pattern` param with `filter` param

README.md, __tests__/test-fetch.js, src/commands/clone.js, src/commands/fetch.js, src/commands/pull.js, src/commands/push.js, src/index.d.ts, src/models/GitConfig.js
BREAKING CHANGE: The `autoTranslateSSH` feature has been removed since it's kind of hacky, and it's trivial to implement your own version using the `data.suggestion` property of the `UnknownTransportError` when something fails.
=> chore: remove the 'autoTranslateSSH' feature

README.md, __tests__/test-addNote.js, __tests__/test-hashBlob.js, __tests__/test-packObjects.js, __tests__/test-readBlob.js, __tests__/test-readNote.js, __tests__/test-readObject.js, __tests__/test-walk.js, src/commands/hashBlob.js, src/commands/packObjects.js, src/commands/readBlob.js, src/commands/readNote.js, src/commands/readObject.js, src/commands/writeObject.js, src/index.d.ts, src/models/GitWalkerFs.js, src/models/GitWalkerRepo.js, src/utils/mergeTree.js, src/utils/resolveBlob.js
BREAKING CHANGE: Any functions that returned `Buffer` objects now instead return `Uint8Array` objects. This is so we can eventually drop the bloated `Buffer` browser polyfill.
=> chore: return Uint8Arrays instead of Buffers

README.md, src/commands/fetch.js
BREAKING CHANGE: As a historical accident, `message` events were trimmed. This was lossy and removed valuable information, such as an `'\r'` by itself, which is a signal to update the existing line instead of appending a new one. The `rawmessage` event was added as a temporary workaround to expose the untrimmed data. The `rawmessage` event has been removed and from now on, `message` events emit the full untrimmed data.
=> chore: 'message' events are no longer trimmed

README.md, __tests__/__helpers__/generate-docs.js, karma.conf.js, package-lock.json, package-scripts.js, package.json, rollup.config.js
BREAKING CHANGE: The `internal-apis` are no longer included in the npm package. I never really intended that; they were just for running unit tests. Also, I renamed `dist/for-future/isomorphic-git/index.js` to `dist/index.js` and `dist/for-node/isomorphic-git/index.js` to `dist/index.cjs`.
And I removed the `jasmine` fallback. I'm sorry `jest` uses native modules, but it's just _too good_ not to use and maintaining a fallback test runner is an added complication.
=> chore: cleanup 'dist' directory

package-lock.json, package.json
Oh hey look, we can get rid of our `agadoo` fork! https://github.com/Rich-Harris/agadoo/pull/7#issuecomment-570266090
=> chore(dev-deps): upgrade to agadoo 2.0.0

src/commands/fastCheckout.js
This fixes the over-zealous warnings about Git Pull in Studio, ie.
1. click Git Pull button
2. modify a file
3. click Git Pull button again
4. you get warnings even though literally nothing has changed since the last pull 🤦‍♂
=> fix(fastCheckout): don't treat modified files as conflicted unless the file would actually change

README.md, src/commands/checkout.js
corresponds to #1017. Since `fastCheckout` gets deleted that won't merge very well.
=> fix(checkout): don't treat modified files as conflicted unless the file would actually change

__tests__/test-readObject.js, __tests__/test-writeObject.js, src/commands/readObject.js, src/commands/writeObject.js, src/utils/AsyncIterator.js
BREAKING CHANGE: `readObject` and `writeObject` have been updated to use the same object schemas used in `readCommit`, `readTree`, and `readTag`. (The main change is trees are simply arrays now, rather than objects with a `.entries` property.) The types returned by `readObject` also form a proper discriminated union so TypeScript will infer the type of `.object` given `.format` and `.type`.
=> chore: improve `readObject` and `writeObject` typings

README.md, __tests__/__helpers__/generate-docs.js, package-scripts.js, src/commands/STAGE.js, src/commands/TREE.js, src/commands/WORKDIR.js, src/commands/fetch.js, src/commands/getRemoteInfo.js, src/commands/log.js, src/commands/merge.js, src/commands/pack.js, src/commands/packObjects.js, src/commands/push.js, src/commands/readCommit.js, src/commands/readObject.js, src/commands/readTag.js, src/commands/readTree.js, src/commands/status.js, src/commands/typedefs.js, src/commands/types.js, src/commands/walk.js, src/commands/writeCommit.js, src/commands/writeObject.js, src/commands/writeTag.js, src/commands/writeTree.js, src/index.js, src/utils/mergeTree.js
- Moves all the shared types to `typedefs.js`
- Fixes the type (and documentation) of `status` to include `*undeleted* and `*undeletemodified`
- Renames some of the return types for consistency (`MergeReport` -> `MergeResult`, `FetchResponse` -> `FetchResult`, everything is a `Result` now)
=> chore: deduplicate JSDoc types

__tests__/test-config.js, __tests__/test-hosting-providers.js, __tests__/test-merge.js, __tests__/test-push.js, cli.js, package-scripts.js, src/api/addNote.js, src/api/push.js, src/commands/push.js, src/commands/typedefs.js, src/models/GitError.js, src/wire/parseReceivePackResponse.js
BREAKING CHANGE: the `push` function now throws if any of the refs on the remote were not updated successfully. It also returns a nicely typed result object organized by ref, rather than a loose collection of strings organized by outcome.
Bonus: the entire `__tests__` folder now type-checks! And will continue to do so because I added it to the linting step.
=> chore(push): improve schema design of PushResult

src/commands/listCommitsAndTags.js, src/commands/listObjects.js, src/commands/pack.js, src/commands/uploadPack.js, src/managers/GitConfigManager.js, src/managers/GitIgnoreManager.js, src/managers/GitIndexManager.js, src/managers/GitRefManager.js, src/managers/GitShallowManager.js, src/models/GitWalkerFs.js, src/models/GitWalkerIndex.js, src/models/GitWalkerRepo.js, src/storage/expandOid.js, src/storage/expandOidLoose.js, src/storage/expandOidPacked.js, src/storage/hasObject.js, src/storage/hasObjectLoose.js, src/storage/hasObjectPacked.js, src/storage/readObject.js, src/storage/readObjectLoose.js, src/storage/readObjectPacked.js, src/storage/writeObject.js, src/storage/writeObjectLoose.js, src/utils/mergeTree.js
one of the reasons for the new `src/api` directory is to _always_ cast the input to a `FileSystem` there. So we can be certain that everywhere else it's a `FileSystem` not an `FsClient`
=> chore: remove extra FileSystem casts

README.md, __tests__/test-submodules.js, src/api/checkout.js, src/api/clone.js, src/api/pull.js, src/api/statusMatrix.js, src/commands/checkout.js, src/commands/clone.js, src/commands/pull.js
BREAKING CHANGE: The `newSubmoduleBehavior` parameter has been removed and is now the default and only behavior, because it is good. And the `noSubmodules` parameter has been removed and is also the default and only behavior. (This only affects you if you a) liked seeing the console warnings or b) were using `statusMatrix` to traverse submodules for some reason.)
=> chore: make newSubmoduleBehavior and noSubmodules the default behavior

__tests__/__fixtures__/test-fetch-cors.git/config, __tests__/__fixtures__/test-fetch.git/config, __tests__/__fixtures__/test-hosting-providers.git/config, __tests__/__fixtures__/test-issue-84.git/config, __tests__/test-clone.js, __tests__/test-hosting-providers.js, docs/headers.md, src/api/clone.js, src/api/fetch.js, src/api/getRemoteInfo.js, src/api/pull.js, src/api/push.js, src/commands/clone.js, src/commands/fetch.js, src/commands/pull.js, src/commands/push.js, src/managers/GitRemoteHTTP.js
BREAKING CHANGE: The URL that's provided is now the URL that's used; no longer will they be "fixed" to end with `.git` since sometimes that actually makes things worse, and subverts user expectations. Accordingly, the `noGitSuffix` parameter has been removed since it's the default behavior. Furthermore, the `User-Agent` is now totally in the user's hands, because it is just a minefield, and I'm done trying to make sense of it. I added a Headers page to the docs documenting what I know about User-Agent + GitHub + CORS + Chrome bugs.
=> chore: remove automatic URL mangling and User-Agent setting

README.md, src/api/addNote.js, src/api/annotatedTag.js, src/api/commit.js, src/api/merge.js, src/api/pull.js, src/api/removeNote.js, src/commands/addNote.js, src/commands/annotatedTag.js, src/utils/normalizeAuthorObject.js, src/utils/normalizeCommitterObject.js
BREAKING CHANGE: The `author.date`, `committer.date`, `tagger.date` parameters were removed in favor of `author.timestamp`, `comitter.timestamp`, `tagger.timestamp` in order to be clear about what is actually written and better reflect the return types in `readCommit`, `log`, and `readTag`.
=> chore: remove date option from author/committer/tagger

__tests__/test-push.js, declaration.tsconfig.json, docs/onAuth.md, docs/onAuthFailure.md, docs/onAuthSuccess.md, package.json, src/builtin-browser/http.js, src/builtin-node/http.js, src/managers/GitRemoteHTTP.js, src/typedefs.js
The typings for `onAuth` were not what I thought they were 🤦‍♂ . I should consider typechecking all the `.md` files, even the ones that aren't auto-generated. That wouldn't have caught this though, since the page for `onAuth` doesn't actually use `git.clone({ onAuth })` anywhere. :/
And, while I was at it, I went ahead and changed the typings for `onAuthSuccess` and `onAuthFailure` to match (plain arguments instead of an argument object).
Aaaand I generate a `dist/http.d.ts` :eyeroll: oh typescript.
=> chore: fix onAuth typings, add an http.d.ts

__tests__/__helpers__/copy-to-website.js, __tests__/__helpers__/generate-docs.js, package-lock.json, package-scripts.js, package.json, webpack.config.js, website/core/Footer.js, website/pages/en/index.js, website/siteConfig.js, website/static/css/custom.css, website/static/js/.gitignore, website/static/js/try-it-out-giturl.js, website/static/js/tutorial.js
- just dump entire package tarball into the `website/js/isomorphic-git` folder.
- tweaks to homepage
- make Features link to docs
- don't throw error in console about the scrollIntoView thing
- make Try It Out thing a little nicer looking
- tweaks to other pages
- don't load the twitter JavaScript on regular docs pages because Firefox proudly announces it blocked a social tracker on the page!!! Sheesh. I just wanted to embed a tweet, not destroy users privacy 🤕.
- ditch clicky.com analytics since I wasn't using it anyway. And Firefox blocks it.
- try a new analytics called Plausible.io which sounds privacy-conscious and collects way less data. I really just want to know a couple things:
- referers (how did people hear about isomorphic-git? aka Hacker News, blog posts)
- what pages are …
=> chore: fix the website to use the new import paths

src/api/clone.js, src/api/fastForward.js, src/api/fetch.js, src/api/getRemoteInfo.js, src/api/push.js
=> fix: throw a helpful error if `http` argument is missing

src/api/add.js, src/api/addNote.js, src/api/checkout.js, src/api/clone.js, src/api/commit.js, src/api/fastForward.js, src/api/listFiles.js, src/api/merge.js, src/api/pull.js, src/api/remove.js, src/api/removeNote.js, src/api/resetIndex.js, src/api/status.js, src/api/statusMatrix.js, src/api/walk.js, src/commands/STAGE.js, src/commands/WORKDIR.js, src/commands/addNote.js, src/commands/checkout.js, src/commands/clone.js, src/commands/commit.js, src/commands/listFiles.js, src/commands/merge.js, src/commands/pull.js, src/commands/removeNote.js, src/commands/walk.js, src/managers/GitIndexManager.js, src/models/FileSystem.js, src/models/GitWalkerFs.js, src/models/GitWalkerIndex.js
TLDR: If you're doing a bunch of git commands in a loop, you might see a performance regression. File an issue letting me know what you're doing in a loop, and I'll figure out how to speed it up again.
Since some commit a while ago, we've been caching the parsed `.git/index` data since it's needed constantly during `walk`. But we were caching it keyed by `fs` and `filepath`. And... well, in situations where `fs` is in the browser or in memory, and you do funny things with it like wipe it or switch out the files for a different set of files, then `fs` isn't very reliable as a caching key. Because even though the `fs` object reference might be the same, it could be holding a very different file system.
To fix this, I'm relaxing the caching so we only hold onto the cached `.git/index` for …
=> fix: cache per command rather than per 'fs' instance

__tests__/test-push.js, src/errors/HttpError.js, src/managers/GitRemoteHTTP.js
=> feat: include data.response on all HttpErrors (not just on SmartHttpErrors)

README.md
Was looking at this library and noticed that noGitSuffix was removed in version 1.0 so was a bit confused about this comment in the README.
Can't run the `npm run add-contributor` command for some reason. nps is broken for me.
=> fix(docs): `noGitSuffix` is no longer needed

src/commands/push.js
This is a very naïve proposition to fix #1136. It works on the two projects we tried it on but it's just a conversation starter on how to fix this.
=> perf(push): don't send any objects if commit is already on remote

cli.js, src/commands/listObjects.js
@hsablonniere 
This speeds up `listObjects` when there's a lot of commits by never revisiting an object that's already been visited. Should fix #1138
921 commits
12441 objects
42.219 seconds
921 commits
12441 objects
2.422 seconds
=> perf(push): short-circuit recursion in listObjects

__tests__/__helpers__/can-i-skip-tests.js, __tests__/__helpers__/generate-docs.js, __tests__/__helpers__/karma-translate-browser.js, __tests__/__helpers__/set-TRAVIS_PULL_REQUEST_SHA.js, karma.conf.js
Slipped by me the first go-around because that script is in the `__tests__` directory.
=> chore: fix generate-docs.js to use 'main' instead of 'master'

README.md
> git-app-manager - install "unhosted" websites locally by git cloning them
The link for the `git-app-manager` on the README looks dead.
I think this is the matching link: https://git-app-manager.now.sh/ .
It was posted here https://github.com/isomorphic-git/isomorphic-git/issues/97#issuecomment-381365557 by @wmhilton
=> Remove dead link from README.md

package-scripts.js
I noticed that `package.json` had a `format: nps format` command, but `nps` did not have a format command itself. This PR adds that `nps` command
Closes #1174
=> chore(build): adds nps format command, per package json

package-lock.json, package-scripts.js, package.json
Yet another tool needs to be updated to track 'main' instead of 'master.
=> chore: update bundlewatch to track 'main' branch

package-lock.json, package.json, src/models/GitPackIndex.js, src/utils/BufferCursor.js, src/utils/applyDelta.js, webpack.config.js
Replaces the `git-apply-delta` dependency with my own code. Shaves a little over a 1KB off the bundle gzip size (68.73KB -> 67.59KB), and eliminates the following direct and indirect dependencies:
- git-apply-delta@0.0.7
- varint@0.0.3
- bops@0.0.7
- to-utf8@0.0.1
- base64-js@0.0.2
Results are mixed as to whether my version is _faster_ but the speed is negligible anyway. 
cloning https://github.com/git/git.git
my git-apply-delta: 10s
old git-apply-delta: 11s
total time: 4 minutes
cloning https://gitlab.com/gitlab-org/gitlab.git
my git-apply-delta: 87s
old git-apply-delta: 79s
total time: 25 minutes
The _real_ reason I did this, is I'm considering implementing xdelta compression so we can generate efficient sized packfiles (which I consider a prerequisite to adding garbage collection), and …
=> perf: replace git-apply-delta with hand-rolled code

src/utils/deflate.js
While working on my React Native app, I kept finding myself running into `<Intermediate Value>.stream is not a function` errors. After some investigating, I realized that it was thanks to React Native's `Blob` supporting constructors but not the `stream` method. However, it _does_ support `CompressionStream`. As such, it was defaulting to use `browserDeflate`, which was causing errors to be thrown.
I thought I could work around this by polyfilling `Blob.stream`:
```javascript
const streams = require('web-streams-polyfill/ponyfill');
const stream = function stream() {
let position = 0;
// eslint-disable-next-line @typescript-eslint/no-this-alias
const blob = this;
return new streams.ReadableStream({
type: 'bytes',
autoAllocateChunkSize: 524288,
pull: function(controller) {
const v = …
```
=> fix(react-native): fix for "<Intermediate Value>.stream is not a function" errors in React Native

.all-contributorsrc, README.md, __tests__/test-fetch.js, src/commands/fetch.js
Addresses my comment https://github.com/isomorphic-git/isomorphic-git/issues/714#issuecomment-688215101
I guess there is no ref information to update on download. Not 100% sure about this fix, but the test definitely catches it.
Would it be better to skip calling `updateRemoteRefs` rather than calling with an empty Map?
=> fix(fetch): fetching a specific commit hash with `singleBranch: true`

README.md, src/utils/deflate.js
I guess there were 2 PRs opened before master was renamed to main, and when those two PRs were merged, they landed in the wrong branch.
One of these 2 commits is a fix for react-native which is not in the currently released 1.8.0 version. I've just hit the problem, and by pure random fluke, found the fix. I'd be delighted to see 1.8.1 shipped with that fix included! :-)
=> Two commits from master missing in main

src/commands/clone.js
The clone command does not pass the corsProxy setting to the internal _fetch call. As a result, the _fetch command does an unnecessary call to lookup the corsProxy setting again. Additionally, it performs that lookup even when the value is explicitly set to false.
This change matches the behavior of the fetch command, which does pass the corsProxy setting to the internal _fetch call.
=> fix: propagate corsProxy setting on clone command to internal _fetch call

src/api/getRemoteInfo.js
Fixes #1274.
Unfortunately, I can't run the tests locally due to #1158.
I hope this is how the types are handled by this project, I couldn't find any other type definitions. Please let me know if this works for you or if I should change something :smile_cat:
=> fix: add HEAD to GetRemoteInfoResult type.

src/commands/log.js
I hit an error due to this - I somehow got into a situation where `tips` was empty before the check for `tips.length === 0`, so `pop` returned an `undefined`.
This change keeps the logic identical - there's no reason to try to execute the while loop when there are no commits to process. The only difference is that there's a small chance `tips.sort` is called on an empty array, which is a no-op anyway.
I didn't add myself as a contributor as I have another PR open (#1247) where I did.
=> fix(git-log): check commit array before popping

src/api/walk.js
As pointed out in #1313, the `entries` parameter of the `WalkerMap` callback may contain `null` elements. #1314 addressed this issue, which seemingly resulted in the correct type, but broke the docs generator. I've replaced the type annotation with a semantically identical one that doesn't break the docs generator.
=> fix: signature of WalkerMap

__tests__/test-add.js, src/api/add.js, src/models/FileSystem.js, src/utils/posixifyPathBuffer.js
If backslashes are detected in return value of fs.readlink, change them to forward slashes. This logic is handled by the new posixifyPathBuffer helper, which filters the return value of fs.readlink.
I've also added a test to verify that symlinks can be added to the repository and that the contents of the symlink is the target path in posix form.
closes #1381
=> posixify symlink path when adding file to repository

src/commands/log.js
Declaring it after the return statement is a little confusing and can trip up some tools - I am using [babel-plugin-transform-async-to-promises](https://npmjs.com/package/babel-plugin-transform-async-to-promises) which [hit an error](https://github.com/mmkal/plv8-git/pull/87) when updating isomorphic-git because of this.
=> fix: move `endCommit` above return statement

src/utils/git-list-pack.js
fix #1399
There is no `.ended` property on StreamReader. So that check always fails. (There's an `._ended` but it's private.) So there's a chance that `Inflate.push(undefined, true)` happens, in which case pako would might be trying to get length of undefined.
=> fix: "TypeError: Cannot read property 'length' of undefined" at Inflate.push

src/models/GitWalkerFs.js, website/versioned_docs/version-1.x/log.md, website/versioned_docs/version-1.x/walk.md
Addresses bug https://github.com/stoplightio/platform-internal/issues/9154 in Studio Desktop, where all executable files have their mode changed to non-executable in the git index on Windows.
=> fix(statusMatrix, walk): don't remove the executable bit from file mode (Windows-only bug)

__tests__/test-clone.js, src/commands/checkout.js
This PR fixes a bug introduced by https://github.com/isomorphic-git/isomorphic-git/commit/64506265ff1cb7c0ebe56472705239fb8d636d2e. When cloning a repo, the remote tracking branch was not setup anymore cause of the change made. By making the `checkout` command set `track` to `true` by default (and not only on the API layer), it should fix the issue.
=> fix: set remote tracking branch on clone

.all-contributorsrc, README.md, src/errors/UnknownTransportError.js
The `suggestion` parameter in `UnknownTransportError` is optional (or at least it can be `undefined`), but it was declared as required in JSDocs.
https://github.com/isomorphic-git/isomorphic-git/blob/82433d2c4866c14657444c3d18554ba2dd365aee/src/managers/GitRemoteManager.js#L61
=> fix: suggestion can be undefined in UnknownTransportError

__tests__/test-clone.js, docs/faq.md, docs/http.md, src/http/node/index.js, src/typedefs-http.js
resolves #1491
- pass agent parameter to underlying http client
- update reference docs to include new parameter
- update faq to show how to wrap built-in http plugin to inject an agent
=> feat(http): Added agent parameter to request function of http plugin for Node.js

.gitignore, README.md, __tests__/test-exports.js, __tests__/test-updateIndex.js, docs/alphabetic.md, src/api/updateIndex.js, src/errors/InvalidFilepathError.js, src/index.js, src/models/GitIndex.js, website/sidebars.json, website/versioned_docs/version-1.x/alphabetic.md, website/versioned_docs/version-1.x/updateIndex.md, website/versioned_sidebars/version-1.x-sidebars.json
closes #1494
I've added a new API, which is the `updateIndex` API. This is based on the [git update-index](https://git-scm.com/docs/git-update-index) command.
The current implementation allows for adding, removing, force-removing files on disk, or files which are virtual and only live in the object database. The latter use case covers `git update-index --cacheinfo <mode>,<object>,<file>`.
I'm throwing errors based on how `git update-index` throws. I was back-and-forth on adding new error types, but wasn't sure so I worked with what was already there.
I've added quite some tests to it, and tested this new API locally already with the tool that I'm building and seems to work like it should.
=> feat: add updateIndex API

__tests__/test-updateIndex.js, src/api/updateIndex.js
I noticed I had a small oversight inside the `updateIndex` API. 
- Removing a directory should throw an error if `force` was not used.
- Removing a directory with `force` should not remove all files inside that directory.
This PR fixes both issues and adds tests for both.
=> fix(updateIndex): prevent removing directories

.vscode/launch.json, __tests__/test-add.js, __tests__/test-statusMatrix.js, src/api/add.js, src/api/statusMatrix.js, website/versioned_docs/version-1.x/add.md, website/versioned_docs/version-1.x/statusMatrix.md
see https://github.com/isomorphic-git/isomorphic-git/issues/1515
create a boolean `force` param for add (equivalent of `git add --force`...add it to the index even if it would match the .gitignore)
create a boolean `ignored` param for statusMatrix (it already returns anything in the index, even if ignored, but would NOT show new files if they are ignored).  This allows for that use case
---
> note 1: the `git status --ignored` flag was at some point modfied to take arguments.  
This hard to implement as an object with a default, so I left it as a boolean and it's doing "traditional"
see https://git-scm.com/docs/git-status
My recommendation would be that if you ever wanted those, you'd have another prop on the object called ignored-mode that defaults to "traditional" and implements all …
=> feat: add --force and statusMatrix --ignored

src/api/add.js
```
MissingParameterError: The function requires a "filepaths" parameter but none was provided.
```
There is no such parameter as filepaths... there is a filepath, hence the PR. 
Also, we are not following any case convention :/ , corsProxy and singleBranch are came cased, but filepath is lower cased. I propose deprecating and printing a deprecation warning.
To make matters worse filePath is not a normal file path... a path relative to the git repo. perhaps it should be called realtivePath instead.
=> fix: Assert parameter is confusing... fix

.all-contributorsrc, README.md, package-lock.json, package.json
This PR updates `semantic-release` to close #1266 and `@semantic-release/exec` to close #1086. This also fixes the problems reported using npm 7 or later about peer dependencies:
This is the furthest we can upgrade with Node.js v12:
- `semantic-release@>=18` requires Node.js v14.
See https://github.com/semantic-release/semantic-release/releases/tag/v18.0.0.
- `@semantic-release/exec@>=6` requires Node.js v14.  
See https://github.com/semantic-release/exec/releases/tag/v6.0.0.
=> chore(deps-dev): bump semantic-release and @semantic-release/exec

website/package-lock.json
This PR updates `extend` in `/website` to close #993. The release fixes prototype pollution and poses low risk.
v3.0.2 is still the latest version:
```
$ npm show extend@3 version
extend@3.0.0 '3.0.0'
extend@3.0.1 '3.0.1'
extend@3.0.2 '3.0.2'
```
We are still using v3.0.1:
```
$ npm ls 'extend@<=3.0.1'
```
=> chore(deps): bump extend from 3.0.1 to 3.0.2 in /website

website/packages/codemirrorify/package-lock.json
This PR is similar to #1537.
npm 6 does not reliably update dependencies. This PR rewrites `website/packages/codemirrorify/package-lock.json` to use `"lockfileVersion": 2` which allows us to use npm 7 and 8 and save time updating our dependencies.
The file was generated by running these commands in the `website/packages/codemirrorify` directory:
```
npm install -g npm@latest
npm install --package-lock-only
```
Please see the notes in #1537.
=> chore: Rewrite website/packages/codemirrorify/package-lock.json to use lockfileVersion 2

website/package-lock.json
npm 6 does not reliably update dependencies. This PR rewrites `website/package-lock.json` to use `"lockfileVersion": 2` which allows us to use npm 7 and 8 and save time updating our dependencies.
The file was generated by running these commands in the `website` directory:
```
npm install -g npm@latest
npm install --package-lock-only
```
Here is an example from #994 to update `js-yaml` in `website`.
If we use npm 6 the packages are not reliably updated:
```
$ npm --version
6.14.16
$ npm ci
[Evidence of packages installing]
$ npm ls js-yaml
.../isomorphic-git/website
├─┬ alex@7.1.0
│ └─┬ unified-engine@6.0.1
│   └── js-yaml@3.12.0                          [We can update v3.12.0]
└─┬ docusaurus@1.14.0
├─┬ cssnano@4.1.10
│ └─┬ cosmiconfig@5.2.1
│   └── js-yaml@3.13.1 …
```
=> chore: Rewrite website/package-lock.json to use lockfileVersion 2

website/package-lock.json
This PR updates `js-yaml` in `/website` to close #994. This update is low risk including a new feature, bug fixes, and security patches.
We are still using v3.12.0:
```
npm ls js-yaml
```
The latest 3.x version is 3.14.1:
```
$ npm show 'js-yaml@^3.12.0' version
js-yaml@3.12.0 '3.12.0'
js-yaml@3.12.1 '3.12.1'
js-yaml@3.12.2 '3.12.2'
js-yaml@3.13.0 '3.13.0'
js-yaml@3.13.1 '3.13.1'
js-yaml@3.14.0 '3.14.0'
js-yaml@3.14.1 '3.14.1'
```
=> chore(deps): bump js-yaml from 3.12.0 to 3.14.1 in /website

package-lock.json
This PR updates `minimisted` to close #1391. The release is low risk that updates CI and the transitive dependencies.
v2.0.1 is still the latest version:
```
$ npm show minimisted@2 version
minimisted@2.0.0 '2.0.0'
minimisted@2.0.1 '2.0.1'
```
We are still using v2.0.0:
```
$ npm ls minimisted
```
=> chore(deps): bump minimisted from 2.0.0 to 2.0.1

__tests__/test-GitIndex.js, package-lock.json, package.json, website/versioned_docs/version-1.x/add.md, website/versioned_docs/version-1.x/statusMatrix.md, x.sh
This PR should be reviewed after #1538.
This PR will hopefully improve the CI pipeline stability by updating Karma and the related packages. In this PR we:
- bump karma from 2.0.5 to 6.3.18
- bump karma-browserstack-launcher from 1.5.1 to 1.6.0
- bump karma-chrome-launcher from 3.1.0 to 3.1.1
- bump karma-firefox-launcher from 1.2.0 to 2.1.2
- bump karma-jasmine bump from 2.0.1 to 5.0.0
- bump karma-junit-reporter from 1.2.0 to 2.0.1
- bump jasmine-core from 3.4.0 to 3.99.1
- Update two assertions that compare an `ArrayBuffer` using @strangedev's fix from 5c38fe61a783808d779207490fc6459319130711 in [#1386](https://github.com/isomorphic-git/isomorphic-git/pull/1386).
I have reviewed the release notes for each package. The following is a summary of how we are **not affected** by the …
=> chore(deps-dev): bump karma, jasmine, and related dependencies

package-lock.json
This PR updates `eslint-config-prettier` to close #1395. This is a low risk update that adds a few features. We can't upgrade to v7.x until we update `eslint`.
We are still using v6.10.0:
```
$ npm ls eslint-config-prettier
```
We can update to the latest 6.x version, 6.15.0:
```
$ npm show 'eslint-config-prettier@>=6.10.0' version
eslint-config-prettier@6.10.0 '6.10.0'
eslint-config-prettier@6.10.1 '6.10.1'
eslint-config-prettier@6.11.0 '6.11.0'
eslint-config-prettier@6.12.0 '6.12.0'
eslint-config-prettier@6.13.0 '6.13.0'
eslint-config-prettier@6.14.0 '6.14.0'
eslint-config-prettier@6.15.0 '6.15.0'
eslint-config-prettier@7.0.0 '7.0.0'
```
- When we run `npm run format` there are no issues reported or fixed
=> chore(deps-dev): bump eslint-config-prettier from 6.10.0 to 6.15.0

website/package-lock.json
This PR updates `websocket-extensions` to close #1149. This is a low risk release. The update fixes a security vulnerability.
We are still using v0.1.3:
```
$ npm ls websocket-extensions
```
The latest version is still 0.1.4:
```
$ npm show 'websocket-extensions@>=0.1.3' version
websocket-extensions@0.1.3 '0.1.3'
websocket-extensions@0.1.4 '0.1.4'
```
=> chore(deps): bump websocket-extensions from 0.1.3 to 0.1.4 in /website

package-lock.json
This PR updates `ajv` to close #1482. This is a low risk update with no breaking changes in the changelog.
We are still using v6.6.2 and other stale versions:
```
$ npm ls ajv
```
v6.12.6 is still the latest version:
```
$ npm show 'ajv@^6.6.2' version
ajv@6.6.2 '6.6.2'
ajv@6.7.0 '6.7.0'
ajv@6.8.0 '6.8.0'
ajv@6.8.1 '6.8.1'
ajv@6.9.0 '6.9.0'
ajv@6.9.1 '6.9.1'
ajv@6.9.2 '6.9.2'
ajv@6.10.0 '6.10.0'
ajv@6.10.1 '6.10.1'
ajv@6.10.2 '6.10.2'
ajv@6.11.0 '6.11.0'
ajv@6.12.0 '6.12.0'
ajv@6.12.1 '6.12.1'
ajv@6.12.2 '6.12.2'
ajv@6.12.3 '6.12.3'
ajv@6.12.4 '6.12.4'
ajv@6.12.5 '6.12.5'
ajv@6.12.6 '6.12.6'
```
=> chore(deps): bump ajv from 6.6.2 to 6.12.6

website/packages/codemirrorify/package-lock.json
This PR updates `acorn` to close #1100. The release is low risk update. The changes to `acorn` modified how regular expressions are handled to improve security/stability.
We are updated to v6.4.2 which is the latest 6.x version:
```
$ npm show 'acorn@^6.4.0' version
acorn@6.4.0 '6.4.0'
acorn@6.4.1 '6.4.1'
acorn@6.4.2 '6.4.2'
```
We are still using v6.4.0:
```
$ npm ls acorn
```
There are more changes to `package-lock.json` file than I would expect but they were caused by `npm update`. It is reproducibly running the following commands which makes me think there are still rough edges with npm v8:
```
npm install -g npm@latest
npm install --package-lock-only
npm update acorn
```
=> chore(deps): bump acorn from 6.4.0 to 6.4.2 in /website/packages/codemirrorify

website/packages/codemirrorify/package-lock.json
This PR updates `ajv` to close #1485. This is a low risk update with no breaking changes in the changelog.
We are still using v6.11.0:
```
$ npm ls ajv
```
v6.12.6 is still the latest version:
```
$ npm show 'ajv@^6.11.0' version
ajv@6.11.0 '6.11.0'
ajv@6.12.0 '6.12.0'
ajv@6.12.1 '6.12.1'
ajv@6.12.2 '6.12.2'
ajv@6.12.3 '6.12.3'
ajv@6.12.4 '6.12.4'
ajv@6.12.5 '6.12.5'
ajv@6.12.6 '6.12.6'
```
=> chore(deps): bump ajv from 6.11.0 to 6.12.6 in /website/packages/codemirrorify

package-lock.json, package.json
This PR updates `markdown-table` to close #1549.
We'll only update to v2.0.0 today. The update to v3 is ESM only. We can defer that update.
`markdown-table` is used in these two files:
- \_\_tests\_\_/\_\_helpers\_\_/generate-docs.cjs
- \_\_tests\_\_/\_\_helpers\_\_/karma-pr-comment-reporter.cjs
If we write the output to a file for v1.1.3 and v2.0.0 the output is identical.
We are still using v1.1.3:
```
$ npm ls markdown-table
```
We'll use v2.0.0 which is the latest 2.x release:
```
$ npm show 'markdown-table@>=1.1.3' version
markdown-table@1.1.3 '1.1.3'
markdown-table@2.0.0 '2.0.0' ⭐️
markdown-table@3.0.0 '3.0.0'
markdown-table@3.0.1 '3.0.1'
markdown-table@3.0.2 '3.0.2'
```
=> chore(deps-dev): bump markdown-table from 1.1.3 to 2.0.0

karma.conf.cjs, package-lock.json
This PR updates `async` to close #1536.
The update from v2.6.1 to v2.6.4 is a low risk change that fixes vulnerability alerts.
We are still using v2.6.1:
```
$ npm ls async@2
```
v2.6.4 is still the latest version:
```
$ npm show 'async@^2.6.1' version
async@2.6.1 '2.6.1'
async@2.6.2 '2.6.2'
async@2.6.3 '2.6.3'
async@2.6.4 '2.6.4'
```
=> chore(deps): bump async from 2.6.1 to 2.6.4

karma.conf.cjs, website/package-lock.json
This PR updates `async` to close #1535.
The update from v2.6.3 to v2.6.4 is a low risk change.
We are still using v2.6.3:
```
$ npm ls async
```
v2.6.4 is still the latest version:
```
$ npm show 'async@^2.6.1' version
async@2.6.1 '2.6.1'
async@2.6.2 '2.6.2'
async@2.6.3 '2.6.3'
async@2.6.4 '2.6.4'
```
=> chore(deps): bump async from 2.6.3 to 2.6.4 in /website

.github/dependabot.yml
As discussed in https://github.com/isomorphic-git/isomorphic-git/pull/1572#issuecomment-1126798804 we can configure Dependabot not to automatically update `puppeteer`.  
We only want to update `puppeteer` when we update the supported version of Chrome.
=> chore: Prevent Dependabot from updating puppeteer

package-lock.json, package.json
This PR updates `karma-verbose-reporter`.
[Comparing tags](https://github.com/usrz/javascript-karma-verbose-reporter/compare/0.0.6...0.0.8) shows that this is a low risk change that adds an elapsed time and a dependency.
We are using 0.0.6:
```
$ npm ls lodash
```
v0.0.8 is the latest version:
```
$ npm show 'karma-verbose-reporter@>=0.0.6' version
karma-verbose-reporter@0.0.6 '0.0.6'
karma-verbose-reporter@0.0.7 '0.0.7'
karma-verbose-reporter@0.0.8 '0.0.8'
```
=> chore(deps): bump karma-verbose-reporter from 0.0.6 to 0.0.8

.github/dependabot.yml, website/package-lock.json
This PR updates `lodash` to close #1469 and lets Dependabot maintain it.
[Comparing tags](https://github.com/lodash/lodash/compare/4.17.15...4.17.21) shows that this is a low risk change including performance, security, and bug fixes.
We are still using v4.17.15:
```
$ npm ls lodash
```
v4.17.21 is still the latest version:
```
$ npm show 'lodash@>=4.17.15' version
lodash@4.17.15 '4.17.15'
lodash@4.17.16 '4.17.16'
lodash@4.17.17 '4.17.17'
lodash@4.17.18 '4.17.18'
lodash@4.17.19 '4.17.19'
lodash@4.17.20 '4.17.20'
lodash@4.17.21 '4.17.21'
```
=> chore(deps): bump lodash from 4.17.15 to 4.17.21 in /website

karma.conf.cjs
This PR attempts to fix the flaky test disconnects when testing using Android 10 on BrowserStack in the CI pipelines.
- Change the global Jasmine (test runner) timeout from 5s to 60s. We change the test timeout in `__tests__/__helpers__/set-test-timeout.js` but it is not called consistently in all tests. The random test order could affect the outcomes.
- Change the BrowserStack timeouts specifically for the Android 10 profile. This follows [the docs](https://github.com/karma-runner/karma-browserstack-launcher#global-options).
- Increase the Karma timeouts based on indirect advice from BrowserStack support shared in [this issue](https://github.com/karma-runner/karma-browserstack-launcher/issues/61).
Run the CI pipeline and hope it works. 🤞
The build failed the first time because the …
=> Increase test timeouts to fix Android 10 disconnects

website/package-lock.json
This PR updates `ini` to close #1284.
[Reviewing the changes](https://github.com/npm/ini/compare/v1.3.5...v1.3.8) shows this is a low risk change including a security patch.
We are using 1.3.5:
```
$ npm ls 'ini@<1.3.8'
```
v1.3.8 is still the latest version:
```
$ npm show 'ini@>=1.3.5' version
ini@1.3.5 '1.3.5'
ini@1.3.6 '1.3.6'
ini@1.3.7 '1.3.7'
ini@1.3.8 '1.3.8'
ini@2.0.0 '2.0.0'
ini@3.0.0 '3.0.0'
```
=> chore(deps): bump ini from 1.3.5 to 1.3.8 in /website

website/packages/codemirrorify/package-lock.json
This PR updates `ini` to close #1285.
[Reviewing the changes](https://github.com/npm/ini/compare/v1.3.5...v1.3.8) shows this is a low risk change including a security patch.
We are using 1.3.5:
```
$ npm ls 'ini@<1.3.8'
```
v1.3.8 is still the latest version:
```
$ npm show 'ini@>=1.3.5' version
ini@1.3.5 '1.3.5'
ini@1.3.6 '1.3.6'
ini@1.3.7 '1.3.7'
ini@1.3.8 '1.3.8'
ini@2.0.0 '2.0.0'
ini@3.0.0 '3.0.0'
```
=> chore(deps): bump ini from 1.3.5 to 1.3.8 in /website/packages/codemirrorify

__tests__/env.d.ts, package-lock.json, package.json
This PR updates `@types/jest` to keep up with `jest`. There is no corresponding Dependabot PR.
We are using Jest 27.x:
```
$ npm ls jest
```
We should be using v27.x of `@jest/types` instead of v24.x:
=> chore(deps): bump @types/jest from 24.0.18 to 27.5.1

.all-contributorsrc, README.md, website/i18n/en.json, website/versioned_docs/version-1.x/mergeDriver.md, website/versioned_sidebars/version-1.x-sidebars.json
This should fix `mergeDriver` not showing up in the docs on the website.
=> fix(docs): add mergeDriver to version 1.x docs

docs/mergeDriver.md, website/versioned_docs/version-1.x/mergeDriver.md
Fixes some minor spelling and grammatical errors in the `mergeDriver` docs. Also cleans up the flow of text a bit.
=> docs(mergeDriver): fix spelling, grammar, and prose

src/utils/mergeTree.js
This should fix an issue where `mergeTree` might report a clean merge even if there was not one. If the most recent merged blob was merged cleanly, `cleanMerge` should still be `false` if previous blobs failed.
=> fix(merge): ensure correct value of cleanMerge

src/models/GitPackIndex.js
A Stoplight customer complained that the count is off by one, which it is.
=> fix(onProgress): the "Resolving deltas" count was off by 1

src/api/walk.js
The walk docs example 2 creates difficult to decipher errors when head is undefined or  a document is empty.
sidenote: ` gitdir` is not required... yet it's marked as required. I was able to figure it out, but a complete example would have helped.
```
import { default as isomorphicGitFsClient } from 'node:fs'
import diff from 'diff-lines'
import { fetch, clone, fastForward, currentBranch, walk, TREE, WORKDIR, STAGE } from 'isomorphic-git'
const http = await import('./node_modules/isomorphic-git/http/node/index.js')
const isomorphicGitWorkingTreeDir = '.'
const gitStatus = async () => {
const ref = 'HEAD'
const trees = [TREE({ ref }), WORKDIR(), STAGE()]
const map = async (filepath, [head, workdir]) => {
return {
filepath,
oid: await head?.oid(),
diff: diff(
(await …
```
=> Handle edge cases in walk diff example

__tests__/test-push.js, src/commands/push.js
resolves #398
Coerce the force flag to true if the oid being pushed matches the oid on the remote.
=> fix(push): force push if no change (oids match)

__tests__/test-branch.js, src/api/branch.js, src/commands/branch.js
=> feat(branch): add force param to overwrite existing branch

src/utils/resolveFilepath.js
While investigating an `ObjectTypeError` (I think not this one), I noticed that this spot is checking for `tree` but reporting `blob` as expected in its message. As I understand it they should be the same; now they are.
=> Report correct expected type in resolveFilePath

docs/snippets.md
This snippet demonstrates how to operate on the worktree using the walk function, thus providing a useful starting point.
=> add snippet to docs for removing untracked files in worktree

package-lock.json, website/package-lock.json, website/package.json
- chore(deps): bump caniuse-lite from 1.0.30001314 to 1.0.30001434
- chore(deps): bump caniuse-lite from 1.0.30001010 to 1.0.30001434 in /website
This PR updates `caniuse-lite` to fix the following warning when we run `npm test`:
```
nps is executing `test.jest` : jest --ci --coverage
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```
=> chore(deps): bump caniuse-lite in / and /website

jest.config.cjs, package-lock.json, package.json
This PR closes #1675. The configuration must be updated to generate the expected output.
The `output` setting was removed in v8.0.0.
=> chore(deps-dev): bump jest-junit from 7.0.0 to 15.0.0

azure-pipelines.yml
We haven't been having any luck with Ubuntu 22.04 in #1678.
This PR upgrades to Ubuntu 20.04 and will hopefully be more stable.
=> chore(ci): Update image from Ubuntu 18.04 to 20.04

README.md
Just adding a small clarification to the readme around `fs/promises` to avoid future confusion following discussion here: https://github.com/isomorphic-git/isomorphic-git/issues/1751
=> note that `fs/promises` doesn't work in the readme

README.md, src/models/FileSystem.js, website/versioned_docs/version-1.x/branch.md, website/versioned_docs/version-1.x/walk.md
These commits allow isomorphic-git to work natively with node's `fs/promises` module as well as any filesystems which only provide promise-based functions, and do not expose a `.promises` object. Fixes the issue seen in #1751.
When `fs.promises` does not exist, we now check to see if an arbitrary command (in this case`fs.readFile`) returns a promise. If it does, the filesystem is identified as a promise-based filesystem and treated accordingly. Otherwise, it is treated as a callback-based filesystem and wrapped using `pify` as before.
These changes result from of a refactor of the code, which hopefully should make extending `FileSystem` easier in the future.
Additionally, I've updated the website docs to match with the ones generated by `jsdoc`.
=> Refactor `FileSystem` and add support for `fs/promises`

.gitattributes
The string "unset" doesn't actually unset them, but sets them to an invalid value.
With this change the attributes will be unset which should have the same effect as before.
----
Please feel free to close this PR if `eol=unset` is entirely intentional. The reason I am proposing this change is merely to help my `gitoxide` validation tool to succeed, and it arrives at 'the wrong' conclusion as it only interprets strings when running `git` on the command-line and "unset" always has to mean "an unset attribute".
=> replace "unset" string value of gitattributes with 'unset' syntax

src/api/listBranches.js, website/versioned_docs/version-1.x/listBranches.md
I thought about the issue and I think returning an empty list when there is no initial commit is correct but unexpected, so I added a note in the api documentation.
=> fix #1650 - Added clarification in the api documentation.

__tests__/test-GitPackIndex.js, __tests__/test-GitPktLine.js, __tests__/test-GitSideBand.js, __tests__/test-clone.js, __tests__/test-wire.js, src/commands/fetch.js, src/models/GitPktLine.js, src/models/GitSideBand.js, src/utils/FIFO.js, src/utils/StreamReader.js, src/wire/parseUploadPackResponse.js
resolves #1847
* rethrow error if error is encountered when reading git-upload-pack response
* don't fail if packfile passed to GitPackIndex.fromPack is truncated
* avoid unnecessary copy of buffer when writing line to packetlines FIFO
* properly close FIFO objects after encountering error line in sideband response
* capture error in GitPktLine#read instead of logging to stdout
=> fix: rethrow error if error is encountered when reading git-upload-pack response

.all-contributorsrc, README.md, src/utils/normalizePath.js
I propose a performance optimization for the `normalizePath` function.
I use `isomorphic-git` to refactor a sfdx plugin I maintained and I was very happy with it as it was running 3 times faster for small to medium repository.
Then I tried with a very big one and I found the performances were dropping.
So I looked at what happened to see where I could tweak my implementation (maybe I can have a smarter `iterate` or `walk` method tailored made).
This is how I discovered that 70% of the time were spent inside the `normalizePath` function.
This PR tries to have a very simple approach and to avoid using regex for this code massively used by the library.
There may be a smarter way to deal with it (do multiple things at the same time, skip things), please advise !
On my specific use cases, this …
=> fix: `normalizePath` performance

src/utils/deflate.js
Turns out that resources are still reported as leaking in Deno if the Compression stream is not closed also.
=> fix: close the test compression stream

.all-contributorsrc, README.md, __tests__/test-GitRefManager.js, src/managers/GitRefManager.js
Adds locking around filesystem operations when reading/writing refs to avoid race conditions.
Fixes https://github.com/isomorphic-git/isomorphic-git/issues/1881.
=> Fix race condition when reading/writing refs

src/api/statusMatrix.js
Affected page: https://isomorphic-git.org/docs/en/statusMatrix
Added two more StatusMatrix examples:
```
*   ["j.txt", 1, 2, 0], // deleted, staged, with unstaged-modified changes (new file of the same name)
*   ["k.txt", 1, 1, 0], // deleted, staged, with unstaged changes (new file of the same name)
```
This status is for when you delete a file, then create a new one of the same name (still in working directory).
I'm not sure what to edit on the "possible combinations" part where it marked with `??`. Maybe something like this?
```
0	 2	0	 ??       -> U   (Untracked)
1	 1	0	 D + ??   -> DU  (Deleted, Untracked)
1	 2	0	 D + ??   -> DM  (Deleted, Modified)
```
In both scenario, we have a file in HEAD, deleted it, add it to INDEX, then created a new file of the same name. The difference is …
=> Update statusMatrix.js: added two more StatusMatrix example

__tests__/__fixtures__/test-empty.git/description, src/wire/parseRefsAdResponse.js
=> fix: handle no-refs response from git-upload-pack for git > 2.41.0

.all-contributorsrc, README.md, __tests__/test-wire.js
The Git wire protocol has a special hack to support returning capabilities on empty repos. As of Git version 1.43 the git-http-backend is using this, which means we need to support it.
=> Handle empty repos which return capabilities

src/models/FileSystem.js
Error when clone a new repo: `Error: The file “index” couldn’t be opened because there is no such file.`
When using in react native with IOS device, the FileSystem missing error code when file not exist, will make an exception. I believe new iOS version return different code: `ENSCOCOAERRORDOMAIN260`
So I added more condition to check status code.
=> Fix issue: The file “index” couldn’t be opened because there is no such file on iOS device

__tests__/__helpers__/find-unused-errors.cjs, __tests__/__helpers__/karma-successful-browsers-reporter.cjs, __tests__/test-addRemote.js, azure-pipelines.yml, karma.conf.cjs, package-lock.json, package.json, tsconfig.json
This pull request updates the dependency `typescript` to the newest version `5.7.3`.
It resolves the type checking issues mentioned in [#2035](https://github.com/isomorphic-git/isomorphic-git/pull/2035#issuecomment-2677593012), where new declaration files for some dependencies were not able to be parsed correctly by an old version of TypeScript.
> It's caused by a descendent dependency `@types/babel__traverse` being declared with version *, which downloads the newest type declaration file `index.d.ts`, whose syntax is not compatible with the old version of TypeScript used in this project (`3.9.0-dev.20200223`).
---
It also resolves new type errors that resulted from the update.
```
nps is executing `test.typecheck` : tsc -p tsconfig.json
__tests__/__helpers__/find-unused-errors.cjs:1:9 - …
```
=> Upgrade TypeScript to newest version

README.md
As the README.md mentions, this is now a community maintained project.
It is unclear who the "I" and "me" in the README.md refers to. Therefore I changed it to the third person.
Also fixes the link to Bill's new GitHub handle.
=> Remove first person from README.md

package-scripts.cjs
This pull request removes an unnecessary duplication for the `test` script definition. This does not affect the behaviour in any way.
=> chore: Remove redundant `test` script definition for CI

package-lock.json
This pull request updates `caniuse-lite` and hides one of the warnings in the build logs.
=> chore: Bump caniuse-lite from 1.0.30001434 to 1.0.30001715

.github/workflows/ci.yml
This pull request improves the GitHub Workflow:
- Reduce the runtime by ~20s by only downloading Chromium when required
- Warn when there are uncommitted changes to the documentation
- Add timeouts to the remaining jobs
- Cancel in-progress runs for the current workflow
- If the GitHub Workflow passes, it should be ready to merge
=> chore: Improve the GitHub Workflow performance and warn when uncommitted changes

.github/workflows/ci.yml
This pull request:
- Limits the number of parallel BrowserStack tests to avoid hitting the account limit
- Fixes the conditional Chromium download. The download is skipped if the environment variables are set to anything (`null`, `''`, or `'false`).
This had been tested and works:
=> chore: Improve BrowserStack test stability in the pipeline

package-lock.json, package.json
This pull request updates bundlewatch from 0.3.2 to 0.4.1.
- The pipeline should pass
- I expect bundlewatch will add a check
=> chore: Update bundlewatch from 0.3.2 to 0.4.1

__tests__/test-merge.js, src/api/merge.js, src/commands/merge.js, src/utils/mergeTree.js, website/versioned_docs/version-1.x/merge.md
Unable to `merge` when the two branches shared **no common ancestor**.  
In Git CLI this is handled with `git merge --allow-unrelated-histories`, but our API always threw `MergeNotSupportedError`, forcing users to resort to manual work-arounds.
* **New flag** – `allowUnrelatedHistories` (default `false`) added to `merge`
* When no merge base is found **and** the flag is `true`, we fall back to the empty-tree OID (`4b825dc6…`) as a synthetic base so the standard three-way merge can proceed.
* **Docs updated** to describe the flag.
* **Tests added** covering:
* Merging unrelated branches that add different files.
* Merging unrelated branches that add the *same* filename with diverging content.
```js
await git.merge({
fs,
dir,
ours: 'main',
theirs: 'other',
allowUnrelatedHistories: true,
})
=> feat(merge --allow-unrelated-histories): adding parameter to merge unrelated branches

__tests__/test-merge.js, src/utils/mergeTree.js
This PR fixes a bug in the mergeTree utility where it didn't properly handle the case when both trees had modifications to the same directory structure. The fix adds specific handling for "tree-tree" merges when both sides have modified the same directory path, preserving the directory structure without creating conflicts for directories themselves.
- Added explicit handling for the case when both sides of a merge contain tree objects at the same path
- Added comprehensive tests for merging branches with nested directory structures
- Ensured proper conflict handling when files with the same path have different content
Added two new test cases:
1. Merging branches with unrelated histories where they add files in different nested directories
2. Merging branches with unrelated histories …
=> fix: mergeTree handles modifications in both trees

.all-contributorsrc, README.md, __tests__/test-stash.js, src/api/stash.js, src/commands/stash.js, src/managers/GitStashManager.js, website/versioned_docs/version-1.x/stash.md
---
**feat:** add `create` operation to `stash`
Adds `op: 'create'` to the `stash` command, which **creates a stash commit without modifying refs or the working directory**.
Updated command, tests, and documentation to include this operation.
=> feat: add 'create' operation to stash API
